const bcrypt=require("bcrypt");const jwt=require("jsonwebtoken");const crypto=require("crypto");const nodemailer=require("nodemailer");const User=require("../models/User");const ExchangeRequest=require("../models/ExchangeRequest");
const normalizeWhatsapp=v=>String(v||"").replace(/[^0-9]/g,"");
const publicUser=(u,wa=null)=>({id:u._id,name:u.name,email:u.email,college:u.college,course:u.course,skills:u.skills,whatsappUnlocked:Boolean(wa),whatsapp:wa||null});
const signToken=u=>jwt.sign({userId:u._id.toString()},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||"7d"});
const mailer=()=>nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});
const validEmail=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
async function register(req,res){try{const {name,email,college,course,skills,whatsapp,password}=req.body;const e=String(email||"").trim().toLowerCase(),w=normalizeWhatsapp(whatsapp);if(!name||!e||!college||!course||!skills||!password||!w)return res.status(400).json({message:"Please complete every field."});if(!validEmail(e))return res.status(400).json({message:"Enter a valid email address."});if(password.length<6)return res.status(400).json({message:"Password must be at least 6 characters long."});if(w.length<10)return res.status(400).json({message:"Enter a valid WhatsApp number with country code."});if(await User.findOne({email:e}))return res.status(409).json({message:"An account with this email already exists."});const passwordHash=await bcrypt.hash(password,12);const u=await User.create({name:String(name).trim(),email:e,college:String(college).trim(),course:String(course).trim(),skills:String(skills).trim(),whatsapp:w,passwordHash});res.status(201).json({message:"Registration successful.",user:publicUser(u),token:signToken(u)});}catch(e){console.error(e);res.status(500).json({message:"Could not create the account."});}}
async function login(req,res){try{const u=await User.findOne({email:String(req.body.email||"").trim().toLowerCase()});if(!u||!(await bcrypt.compare(String(req.body.password||""),u.passwordHash)))return res.status(401).json({message:"Invalid email or password."});res.json({message:"Login successful.",user:publicUser(u),token:signToken(u)});}catch(e){res.status(500).json({message:"Could not log in."});}}
async function me(req,res){const u=await User.findById(req.userId);if(!u)return res.status(404).json({message:"User not found."});res.json({user:publicUser(u)});}
async function updateProfile(req,res){try{const u=await User.findById(req.userId);if(!u)return res.status(404).json({message:"User not found."});const {name,college,course,skills,whatsapp,password}=req.body;if(name)u.name=String(name).trim();if(college)u.college=String(college).trim();if(course)u.course=String(course).trim();if(skills)u.skills=String(skills).trim();if(whatsapp){const w=normalizeWhatsapp(whatsapp);if(w.length<10)return res.status(400).json({message:"Enter a valid WhatsApp number with country code."});u.whatsapp=w;}if(password){if(String(password).length<6)return res.status(400).json({message:"New password must be at least 6 characters long."});u.passwordHash=await bcrypt.hash(String(password),12);}await u.save();res.json({message:"Profile updated.",user:publicUser(u)});}catch(e){res.status(500).json({message:"Could not update the profile."});}}
async function getPeers(req,res){try{const users=await User.find({_id:{$ne:req.userId}}).sort({createdAt:-1});const ids=users.map(u=>u._id);const accepted=await ExchangeRequest.find({status:"accepted",$or:[{fromUser:req.userId,toUser:{$in:ids}},{toUser:req.userId,fromUser:{$in:ids}}]});const unlocked=new Set();accepted.forEach(r=>unlocked.add(r.fromUser.toString()===req.userId?r.toUser.toString():r.fromUser.toString()));res.json({users:users.map(u=>publicUser(u,unlocked.has(u._id.toString())?u.whatsapp:null))});}catch(e){res.status(500).json({message:"Could not load student profiles."});}}
async function requestPasswordReset(req,res){try{const email=String(req.body.email||"").trim().toLowerCase();if(!validEmail(email))return res.status(400).json({message:"Enter a valid email address."});const u=await User.findOne({email});if(!u)return res.json({message:"If an account exists for this email, a reset link has been sent."});if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS||!process.env.SMTP_FROM)return res.status(503).json({message:"Password reset email service is not configured yet."});const raw=crypto.randomBytes(32).toString("hex");u.resetTokenHash=crypto.createHash("sha256").update(raw).digest("hex");u.resetTokenExpires=new Date(Date.now()+30*60*1000);await u.save();const base=(process.env.APP_URL||"http://localhost:5000").replace(/\/$/,"");const link=base+"/pages/reset-password.html?token="+raw;await mailer().sendMail({from:process.env.SMTP_FROM,to:u.email,subject:"Reset your Campus Skill Exchange password",text:"Use this link within 30 minutes to reset your password: "+link,html:"<p>You requested a password reset for Campus Skill Exchange.</p><p><a href=\""+link+"\">Reset your password</a></p><p>This link expires in 30 minutes and can be used only once.</p>"});res.json({message:"If an account exists for this email, a reset link has been sent."});}catch(e){console.error("Password reset email failed:",e.message);res.status(500).json({message:"Could not send the password reset email."});}}
async function resetPassword(req,res){try{const token=String(req.body.token||"");const password=String(req.body.password||"");if(token.length<40||password.length<6)return res.status(400).json({message:"Invalid reset request."});const hash=crypto.createHash("sha256").update(token).digest("hex");const u=await User.findOne({resetTokenHash:hash,resetTokenExpires:{$gt:new Date()}});if(!u)return res.status(400).json({message:"This reset link is invalid or expired."});u.passwordHash=await bcrypt.hash(password,12);u.resetTokenHash=null;u.resetTokenExpires=null;await u.save();res.json({message:"Password reset successful. You can now log in."});}catch(e){res.status(500).json({message:"Could not reset the password."});}}
async function deleteAccount(req,res){try{const password=String(req.body.password||"");const u=await User.findById(req.userId);if(!u)return res.status(404).json({message:"User not found."});if(!password||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({message:"Incorrect password."});await ExchangeRequest.deleteMany({$or:[{fromUser:u._id},{toUser:u._id}]});await u.deleteOne();res.json({message:"Account deleted successfully."});}catch(e){console.error(e);res.status(500).json({message:"Could not delete the account."});}}
module.exports={register,login,me,updateProfile,getPeers,requestPasswordReset,resetPassword,deleteAccount};