const bcrypt=require("bcrypt");const jwt=require("jsonwebtoken");const User=require("../models/User");const ExchangeRequest=require("../models/ExchangeRequest");
const normalizeWhatsapp=v=>String(v||"").replace(/[^0-9]/g,"");
const publicUser=(u,wa=null)=>({id:u._id,name:u.name,email:u.email,college:u.college,course:u.course,skills:u.skills,whatsappUnlocked:Boolean(wa),whatsapp:wa||null});
const signToken=u=>jwt.sign({userId:u._id.toString()},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||"7d"});
async function register(req,res){try{const {name,email,college,course,skills,whatsapp,password}=req.body;const e=String(email||"").trim().toLowerCase(),w=normalizeWhatsapp(whatsapp);if(!name||!e||!college||!course||!skills||!password||!w)return res.status(400).json({message:"Please complete every field."});if(password.length<6)return res.status(400).json({message:"Password must be at least 6 characters long."});if(w.length<10)return res.status(400).json({message:"Enter a valid WhatsApp number with country code."});if(await User.findOne({email:e}))return res.status(409).json({message:"An account with this email already exists."});const passwordHash=await bcrypt.hash(password,12);const u=await User.create({name:String(name).trim(),email:e,college:String(college).trim(),course:String(course).trim(),skills:String(skills).trim(),whatsapp:w,passwordHash});res.status(201).json({message:"Registration successful.",user:publicUser(u),token:signToken(u)});}catch(e){console.error(e);res.status(500).json({message:"Could not create the account."});}}
async function login(req,res){try{const u=await User.findOne({email:String(req.body.email||"").trim().toLowerCase()});if(!u||!(await bcrypt.compare(String(req.body.password||""),u.passwordHash)))return res.status(401).json({message:"Invalid email or password."});res.json({message:"Login successful.",user:publicUser(u),token:signToken(u)});}catch(e){res.status(500).json({message:"Could not log in."});}}
async function me(req,res){const u=await User.findById(req.userId);if(!u)return res.status(404).json({message:"User not found."});res.json({user:publicUser(u)});}
async function updateProfile(req,res){try{const u=await User.findById(req.userId);if(!u)return res.status(404).json({message:"User not found."});const {name,college,course,skills,whatsapp}=req.body;if(name)u.name=String(name).trim();if(college)u.college=String(college).trim();if(course)u.course=String(course).trim();if(skills)u.skills=String(skills).trim();if(whatsapp){const w=normalizeWhatsapp(whatsapp);if(w.length<10)return res.status(400).json({message:"Enter a valid WhatsApp number with country code."});u.whatsapp=w;}await u.save();res.json({message:"Profile updated.",user:publicUser(u)});}catch(e){res.status(500).json({message:"Could not update the profile."});}}
async function getPeers(req,res){try{const users=await User.find({_id:{$ne:req.userId}}).sort({createdAt:-1});const ids=users.map(u=>u._id);const accepted=await ExchangeRequest.find({status:"accepted",$or:[{fromUser:req.userId,toUser:{$in:ids}},{toUser:req.userId,fromUser:{$in:ids}}]});const unlocked=new Set();accepted.forEach(r=>unlocked.add(r.fromUser.toString()===req.userId?r.toUser.toString():r.fromUser.toString()));res.json({users:users.map(u=>publicUser(u,unlocked.has(u._id.toString())?u.whatsapp:null))});}catch(e){res.status(500).json({message:"Could not load student profiles."});}}
module.exports={register,login,me,updateProfile,getPeers};